const reviewData = [
  {
    id: 1,
    starRating: 5,
    reviewerName: "Alex Johnson",
    datePosted: "June 15, 2023 2:32 PM",
    reviewType: "featureRequest",
    reviewText: "I love this app! It works flawlessly and has become an essential part of my daily routine. One thing I would like to see is the ability to add custom categories for better organization. The current categories are great, but having the option to create custom ones would make it even more personalized.",
    likes: 32,
    appVersion: "1.2.3 build 10562",
    deviceName: "Google Pixel 6",
    deviceOS: "Android 13.1",
    deviceType: "mobile",
    chips: ["Original text"]
  },
  {
    id: 1,
    starRating: 5,
    reviewerName: "Don Doe",
    datePosted: "July 25, 2023 5:32 PM",
    reviewType: "featureRequest",
    reviewText: "I love this app! It works flawlessly and has become an essential part of my daily routine. One thing I would like to see is the ability to add custom categories for better organization. The current categories are great, but having the option to create custom ones would make it even more personalized.",
    likes: 32,
    appVersion: "1.2.3 build 10562",
    deviceName: "Google Pixel 6",
    deviceOS: "Android 13.1",
    deviceType: "mobile",
    chips: ["Original text"]
  },
  {
    id: 2,
    starRating: 4,
    reviewerName: "Emily Roberts",
    datePosted: "July 13, 2023 9:15 AM",
    reviewType: "bug",
    reviewText: "Overall, the app is fantastic, but I encountered a small bug where the search feature occasionally doesn't return any results. Fixing this issue would make the app even better! Other than that, the user interface is clean and intuitive, and I love the variety of themes available.",
    likes: 12,
    appVersion: "1.2.1 build 9611",
    deviceName: "iPhone 12 Pro",
    deviceOS: "iOS 15.0",
    deviceType: "mobile",
    chips: []
  },
  {
    id: 3,
    starRating: 5,
    reviewerName: "David Miller",
    datePosted: "July 10, 2023 7:45 PM",
    reviewType: "appreciation",
    reviewText: "This app is a lifesaver! It helped me stay organized and boosted my productivity. I appreciate the team's hard work in creating such a user-friendly and feature-rich app. The dark mode is a game-changer for me, and it's now my go-to app for managing my tasks and schedules.",
    likes: 48,
    appVersion: "1.2.5 build 10562",
    deviceName: "Samsung Galaxy S21",
    deviceOS: "Android 12.1",
    deviceType: "mobile",
    chips: []
  },
  {
    id: 11,
    starRating: 4,
    reviewerName: "Jane Smith",
    datePosted: "July 7, 2023 3:45 PM",
    reviewType: "bug",
    reviewText: "Great app overall, but I noticed a minor bug when trying to edit an existing entry. The changes don't get saved properly. Please address this issue.",
    likes: 20,
    appVersion: "1.2.3 build 10562",
    deviceName: "Samsung Galaxy Note 20",
    deviceOS: "Android 11",
    deviceType: "mobile",
    chips: []
  },
  {
    id: 12,
    starRating: 5,
    reviewerName: "Michael Johnson",
    datePosted: "July 6, 2023 10:00 AM",
    reviewType: "appreciation",
    reviewText: "I absolutely love this app! It has everything I need to stay organized and productive. The dark mode is especially helpful for late-night work sessions. Thank you for creating such an amazing app!",
    likes: 50,
    appVersion: "1.2.4 build 11009",
    deviceName: "iPhone 13 Pro",
    deviceOS: "iOS 16.0",
    deviceType: "mobile",
    chips: ["Highly Recommended"]
  },
  {
    id: 13,
    starRating: 4,
    reviewerName: "Sarah Adams",
    datePosted: "July 5, 2023 6:20 PM",
    reviewType: "featureRequest",
    reviewText: "This app is fantastic, but it would be even better with more color themes. Please consider adding additional color options for more customization.",
    likes: 15,
    appVersion: "1.2.5 build 10562",
    deviceName: "Google Pixel 5a",
    deviceOS: "Android 12.1",
    deviceType: "mobile",
    chips: ["Great UI"]
  },
  {
    id: 14,
    starRating: 3,
    reviewerName: "William Taylor",
    datePosted: "July 4, 2023 12:05 PM",
    reviewType: "bug",
    reviewText: "The app is decent, but there's a bug that causes occasional crashes when using certain features. Please fix this issue for a smoother user experience.",
    likes: 8,
    appVersion: "1.2.1 build 9611",
    deviceName: "OnePlus Nord 2",
    deviceOS: "Android 11",
    deviceType: "mobile",
    chips: []
  },
  {
    id: 15,
    starRating: 5,
    reviewerName: "Olivia White",
    datePosted: "July 3, 2023 9:30 AM",
    reviewType: "appreciation",
    reviewText: "Amazing app! I've been using it for months now, and it has become an indispensable part of my daily routine. The simple and intuitive design makes it easy to manage tasks effectively. Kudos to the developers!",
    likes: 40,
    appVersion: "1.2.2 build 8798",
    deviceName: "iPhone 11",
    deviceOS: "iOS 14.6",
    deviceType: "mobile",
    chips: []
  },
  // Add more reviews...
  {
    id: 4,
    starRating: 5,
    reviewerName: "Sophia Lee",
    datePosted: "July 18, 2023 11:25 AM",
    reviewType: "featureRequest",
    reviewText: "I'm really impressed with this app! It's simple to use, and I love how I can organize my tasks easily. The feature I'd like to request is the ability to set recurring reminders for certain tasks.",
    likes: 25,
    appVersion: "1.2.2 build 8798",
    deviceName: "OnePlus 9",
    deviceOS: "Android 12",
    deviceType: "mobile",
    chips: ["Fantastic"]
  },
  {
    id: 5,
    starRating: 4,
    reviewerName: "James Williams",
    datePosted: "July 17, 2023 4:50 PM",
    reviewType: "bug",
    reviewText: "Overall, the app is great, but I've encountered a bug that sometimes causes the app to freeze when I switch between themes rapidly. Other than that, the app is perfect for managing my tasks.",
    likes: 18,
    appVersion: "1.2.4 build 11009",
    deviceName: "Samsung Galaxy S20",
    deviceOS: "Android 12",
    deviceType: "mobile",
    chips: []
  },
  {
    id: 6,
    starRating: 5,
    reviewerName: "Lily Johnson",
    datePosted: "July 16, 2023 8:15 AM",
    reviewType: "appreciation",
    reviewText: "I can't express how much I love this app! It's made a huge difference in my productivity. The variety of themes and customization options are excellent. Keep up the great work!",
    likes: 35,
    appVersion: "1.2.5 build 10562",
    deviceName: "Google Pixel 4a",
    deviceOS: "Android 12",
    deviceType: "mobile",
    chips: ["Highly Recommended"]
  },
  {
    id: 7,
    starRating: 3,
    reviewerName: "Jack Smith",
    datePosted: "July 15, 2023 6:30 PM",
    reviewType: "bug",
    reviewText: "The app is pretty good, but I encountered a bug where the app occasionally crashes when I have multiple tasks with reminders set. Please fix this issue for a smoother experience.",
    likes: 10,
    appVersion: "1.2.3 build 10562",
    deviceName: "iPhone XR",
    deviceOS: "iOS 15.0",
    deviceType: "mobile",
    chips: []
  },
  {
    id: 8,
    starRating: 4,
    reviewerName: "Ella Adams",
    datePosted: "July 14, 2023 3:20 PM",
    reviewType: "featureRequest",
    reviewText: "This app is great, but I'd love to have the option to add attachments to tasks. It would be helpful to attach files or images to specific tasks for reference.",
    likes: 16,
    appVersion: "1.2.1 build 9611",
    deviceName: "Samsung Galaxy A52",
    deviceOS: "Android 11",
    deviceType: "mobile",
    chips: []
  },
  {
    id: 9,
    starRating: 5,
    reviewerName: "Noah Wilson",
    datePosted: "July 13, 2023 9:00 AM",
    reviewType: "appreciation",
    reviewText: "Absolutely fantastic app! It's incredibly user-friendly, and the sync across devices works flawlessly. It's made organizing my tasks so much easier.",
    likes: 42,
    appVersion: "1.2.5 build 10562",
    deviceName: "iPhone 13",
    deviceOS: "iOS 16.0",
    deviceType: "mobile",
    chips: ["Excellent"]
  },
  {
    id: 10,
    starRating: 4,
    reviewerName: "Oliver Martin",
    datePosted: "July 12, 2023 2:15 PM",
    reviewType: "bug",
    reviewText: "The app is mostly great, but I encountered a bug where the app crashes occasionally during background sync. Fixing this issue would make it even better.",
    likes: 19,
    appVersion: "1.2.2 build 8798",
    deviceName: "OnePlus 8T",
    deviceOS: "Android 11",
    deviceType: "mobile",
    chips: []
  },
];

export default reviewData;